layers:
  - Input:
      shape: [~, ~, num_bands]
  - EfficientNetB2:
      input_shape: [~, ~, num_bands]
  - Conv2DTranspose:
      filters: 112
      kernel_size: [5, 5]
      activation: relu
      padding: same
      strides: 2
  - BatchNormalization:
  - Dropout:
       rate: 0.2
  - Conv2DTranspose:
      filters: 40
      kernel_size: [3, 3]
      activation: relu
      padding: same
      strides: 2
  - BatchNormalization:
  - Dropout:
       rate: 0.2
  - Conv2DTranspose:
      filters: 24
      kernel_size: [5, 5]
      activation: relu
      padding: same
      strides: 2
  - BatchNormalization:
  - Dropout:
       rate: 0.2
  - Conv2DTranspose:
      filters: 16
      kernel_size: [3, 3]
      activation: relu
      padding: same
      strides: 2
  - BatchNormalization:
  - Dropout:
       rate: 0.5
  - Conv2DTranspose:
      filters: 32
      kernel_size: [3, 3]
      activation: relu
      padding: same
      strides: 2
  - BatchNormalization:
  - Dropout:
       rate: 0.5
  - Conv2D:
      filters: num_bands
      kernel_size: [7, 7]
      activation: relu
      padding: same
